### ISSUE TITLE
очень странный способ коммуникации

### ISSUE THREAD

**Issue by juicyfru1t** [divo-player/support#1]
привет, не нашел контактов, но нашел на форуме apple https://developer.apple.com/forums/thread/85769?page=3 

I have the same issue in 2022. Sounds like a poem, eh? The app has been "In Review" status since March 2, 2022. The app store support service did not much help. All you can get is what you are already known about: your app is "In Review". But, wait a minute... Please feel free to reply if you have any other questions!

сообщение, которое как кажется от вас. хотел спросить - удалось ли решить проблему? или приложение так и продолжает висеть?

**Comment by Algashev** [comment]
Привет! Ожидайте, вот и всё решение. Ориентировочно до 3-х месяцев.
